version: '3.4'

services:
  postgres:
    image: registry.cn-beijing.aliyuncs.com/crucialize/postgres-zhts:latest
    environment:
      - POSTGRES_PASSWORD=P4fyWG3LG8PLC9QH5cpArKuu
    networks:
      - mynet
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - pg_volume:/var/lib/postgresql/data
    # hostname: apostgres # shit
    container_name: a-postgres
    restart: always

networks:
  mynet:
    external:
      name: mynet
